# Generated by Django 4.1.2 on 2023-08-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name1',
            new_name='name',
        ),
    ]
